name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      node-version: 14.x

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - run: yarn

      - run: yarn workspace @cisl/io publisher
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: yarn workspace @cisl/io-celio-speaker publisher
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: yarn workspace @cisl/io-celio-transcript publisher
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: yarn workspace @cisl/io-display publisher
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: yarn workspace @cisl/io-speaker publisher
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
