name: Publish

on:
  push:
    branches:
      - test

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      node-version: 14.x

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: yarn

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: masterodin

      - run: yarn workspace @cisl/io publisher
      - run: yarn workspace @cisl/io-celio-speaker publisher
      - run: yarn workspace @cisl/io-celio-transcript publisher
      - run: yarn workspace @cisl/io-display publisher
      - run: yarn workspace @cisl/io-speaker publisher
