name: Test

on: ['push', 'pull_request']

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: create rabbitmq container
      run: docker run -d --rm -p 5672:5672 -p 15672:15672 rabbitmq:3.8-alpine

    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn

    - run: yarn lint || true

    - run: yarn build

    - run: yarn test
